### ISSUE TITLE
Purge excludes classes

### ISSUE THREAD

**Issue by mansoorkhan96** [awcodes/filament-plugin-purge#4]
Purge commands removes certain classes. I have a div with classes `grid grid-cols-2 gap-4 sm:grid-cols-4` and when hit purge command `sm:grid-cols-4` classe is not there same goes for a few more classes. However other classes being included.

```css
/*resources/css/filament-custom.css*/

@config "../../tailwind.filament-custom.config.js";

@tailwind components;
@tailwind utilities;

@layer components {
    .gd-light{
        background: repeating-linear-gradient(-45deg, whitesmoke, whitesmoke 0.5em, #e8e8e8 0.5em, #e8e8e8 1em);
    }

    .gd-dark {
        background: repeating-linear-gradient(-45deg, #303030, #303030 0.5em, #3c3c3c 0.5em, #3c3c3c 1em);
    }
}

.custom-gd {
    @apply gd-light cursor-not-allowed gd-dark;
}
```

```js
// tailwind.filament-custom.config.js

import preset from './vendor/filament/support/tailwind.config.preset'

export default {
    presets: [preset],
    content: [
        // './vendor/filament/**/*.blade.php',
       './resources/views/filament/pages/custom.blade.php',
    ],
}

```

```js
// package.json

"scripts": {
        "build-filament-custom-css": "npx tailwindcss -i resources/css/filament-custom.css -o resources/dist/css/filament-custom.css --minify",
        "purge-filament-custom-css": "npm run build-filament-custom-css && filament-purge -i resources/dist/css/filament-custom.css -o resources/dist/css/filament-custom.css"
    },
```

NOTE: Its not package, Its inside a normal Laravel app.
